devices:
  plug: switch.16amp_smart_plug_with_metering_socket_1

scenes:
  goodnight:
    - device: plug
      action: turn_off

  leaving_home:
    - device: plug
      action: turn_off

  i_am_home:
    - device: plug
      action: turn_on

alerts:
  geyser_max_minutes: 45
  check_interval_minutes: 30
